//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMPS.Office.Word.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPS Branding")]
        public string GraphicsPictureLibraryTitle {
            get {
                return ((string)(this["GraphicsPictureLibraryTitle"]));
            }
            set {
                this["GraphicsPictureLibraryTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Company Logos")]
        public string GraphicsPictureLibraryTitleLogos {
            get {
                return ((string)(this["GraphicsPictureLibraryTitleLogos"]));
            }
            set {
                this["GraphicsPictureLibraryTitleLogos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Class of Insurance")]
        public string MajorPolicyClassesListName {
            get {
                return ((string)(this["MajorPolicyClassesListName"]));
            }
            set {
                this["MajorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Policy Type")]
        public string MinorPolicyClassesListName {
            get {
                return ((string)(this["MinorPolicyClassesListName"]));
            }
            set {
                this["MinorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PreRenewalQuestionareMappings")]
        public string PreRenewalQuestionareMappingsListName {
            get {
                return ((string)(this["PreRenewalQuestionareMappingsListName"]));
            }
            set {
                this["PreRenewalQuestionareMappingsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approved Insurers List")]
        public string ApprovedInsurersListName {
            get {
                return ((string)(this["ApprovedInsurersListName"]));
            }
            set {
                this["ApprovedInsurersListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentsListName {
            get {
                return ((string)(this["GeneralFragmentsListName"]));
            }
            set {
                this["GeneralFragmentsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFITo {
            get {
                return ((string)(this["EmailAddressUFITo"]));
            }
            set {
                this["EmailAddressUFITo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFIFrom {
            get {
                return ((string)(this["EmailAddressUFIFrom"]));
            }
            set {
                this["EmailAddressUFIFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMTP {
            get {
                return ((string)(this["SMTP"]));
            }
            set {
                this["SMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Guide")]
        public string MinorQuestionClassesListName {
            get {
                return ((string)(this["MinorQuestionClassesListName"]));
            }
            set {
                this["MinorQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Category")]
        public string TopLevelQuestionClassesListName {
            get {
                return ((string)(this["TopLevelQuestionClassesListName"]));
            }
            set {
                this["TopLevelQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyFragments")]
        public string PolicyFragmentKeysListName {
            get {
                return ((string)(this["PolicyFragmentKeysListName"]));
            }
            set {
                this["PolicyFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentKeysListName {
            get {
                return ((string)(this["GeneralFragmentKeysListName"]));
            }
            set {
                this["GeneralFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Word Help Content")]
        public string HelpContentListName {
            get {
                return ((string)(this["HelpContentListName"]));
            }
            set {
                this["HelpContentListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage Reporting")]
        public string UsageReportingListName {
            get {
                return ((string)(this["UsageReportingListName"]));
            }
            set {
                this["UsageReportingListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quote Slip Schedules")]
        public string PolicySchedulesListName {
            get {
                return ((string)(this["PolicySchedulesListName"]));
            }
            set {
                this["PolicySchedulesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Claims Procedures")]
        public string LibraryClaimsProcedures {
            get {
                return ((string)(this["LibraryClaimsProcedures"]));
            }
            set {
                this["LibraryClaimsProcedures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("proposal short document titles")]
        public string ListProposalShortDocumentTitles {
            get {
                return ((string)(this["ListProposalShortDocumentTitles"]));
            }
            set {
                this["ListProposalShortDocumentTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPSWordTemplates")]
        public string MainTemplatesLibraryName {
            get {
                return ((string)(this["MainTemplatesLibraryName"]));
            }
            set {
                this["MainTemplatesLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Insurance Renewal Repor" +
            "t.docx")]
        public string TemplateInsuranceRenewalReport {
            get {
                return ((string)(this["TemplateInsuranceRenewalReport"]));
            }
            set {
                this["TemplateInsuranceRenewalReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/{0}")]
        public string aadInstance {
            get {
                return ((string)(this["aadInstance"]));
            }
            set {
                this["aadInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ajgau.onmicrosoft.com")]
        public string tenant {
            get {
                return ((string)(this["tenant"]));
            }
            set {
                this["tenant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83141754-35c8-4bf9-9a1d-c125529856f0")]
        public string clientid {
            get {
                return ((string)(this["clientid"]));
            }
            set {
                this["clientid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ajgau.sharepoint.com/sites/intranet")]
        public string redirecturi {
            get {
                return ((string)(this["redirecturi"]));
            }
            set {
                this["redirecturi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Discovery Guide.docx")]
        public string TemplateDiscoveryGuide {
            get {
                return ((string)(this["TemplateDiscoveryGuide"]));
            }
            set {
                this["TemplateDiscoveryGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Generic Letter.docx")]
        public string TemplateGenericLetter {
            get {
                return ((string)(this["TemplateGenericLetter"]));
            }
            set {
                this["TemplateGenericLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Renewal Letter.docx")]
        public string TemplateInsuranceRenewalLetter {
            get {
                return ((string)(this["TemplateInsuranceRenewalLetter"]));
            }
            set {
                this["TemplateInsuranceRenewalLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\QuoteSlip.docx")]
        public string TemplateQuoteSlip {
            get {
                return ((string)(this["TemplateQuoteSlip"]));
            }
            set {
                this["TemplateQuoteSlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/4f955c1f-62e5-44ef-8da3-051caaa6b103/federation" +
            "metadata/2007-06/federationmetadata.xml")]
        public string TenantMetadataUrl {
            get {
                return ((string)(this["TenantMetadataUrl"]));
            }
            set {
                this["TenantMetadataUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ajgau.sharepoint.com")]
        public string TokenResourceUrl {
            get {
                return ((string)(this["TokenResourceUrl"]));
            }
            set {
                this["TokenResourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPSWordTemplates")]
        public string TemplateLibraryName {
            get {
                return ((string)(this["TemplateLibraryName"]));
            }
            set {
                this["TemplateLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPS Letters")]
        public string LetterLibraryName {
            get {
                return ((string)(this["LetterLibraryName"]));
            }
            set {
                this["LetterLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSSTemplates")]
        public string LocalLibraryName {
            get {
                return ((string)(this["LocalLibraryName"]));
            }
            set {
                this["LocalLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client Facing Documents")]
        public string ClientFacing {
            get {
                return ((string)(this["ClientFacing"]));
            }
            set {
                this["ClientFacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Non Client Facing Documents")]
        public string NonClientFacing {
            get {
                return ((string)(this["NonClientFacing"]));
            }
            set {
                this["NonClientFacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AJG\\CSS Templates")]
        public string LocalPathRoot {
            get {
                return ((string)(this["LocalPathRoot"]));
            }
            set {
                this["LocalPathRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Meeting Agenda.docx")]
        public string TemplateAgenda {
            get {
                return ((string)(this["TemplateAgenda"]));
            }
            set {
                this["TemplateAgenda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ajgau.sharepoint.com/sites/Applications/Templates/")]
        public string SharePointContextUrl {
            get {
                return ((string)(this["SharePointContextUrl"]));
            }
            set {
                this["SharePointContextUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/sites/Applications/Templates/")]
        public string RelativeSitePath {
            get {
                return ((string)(this["RelativeSitePath"]));
            }
            set {
                this["RelativeSitePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\FSG Fragment_letter.docx")]
        public string FragmentFSGLetter {
            get {
                return ((string)(this["FragmentFSGLetter"]));
            }
            set {
                this["FragmentFSGLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\General Advice Warniing Fragment" +
            ".docx")]
        public string FragmentWarning {
            get {
                return ((string)(this["FragmentWarning"]));
            }
            set {
                this["FragmentWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_NewInsr_YesGA" +
            "W_NoFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\FSG Fragment.docx")]
        public string FragmentFSG {
            get {
                return ((string)(this["FragmentFSG"]));
            }
            set {
                this["FragmentFSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Privacy Statement.docx")]
        public string FragmentPrivacy {
            get {
                return ((string)(this["FragmentPrivacy"]));
            }
            set {
                this["FragmentPrivacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Uninsured Risks Checklist.docx")]
        public string FragmentUninsuredRisks {
            get {
                return ((string)(this["FragmentUninsuredRisks"]));
            }
            set {
                this["FragmentUninsuredRisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Important Notices.docx")]
        public string FragmentStatutory {
            get {
                return ((string)(this["FragmentStatutory"]));
            }
            set {
                this["FragmentStatutory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_ExistingInsr_N" +
            "oGAW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_ExistingInsr_N" +
            "oGAW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_ExistingInsr_Y" +
            "esGAW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_ExistingInsr_Y" +
            "esGAW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Service Plan Seg 2 v0.1.docx")]
        public string FragmentServicePlanSeg2 {
            get {
                return ((string)(this["FragmentServicePlanSeg2"]));
            }
            set {
                this["FragmentServicePlanSeg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Service Plan Seg 3 v0.1.docx")]
        public string FragmentServicePlanSeg3 {
            get {
                return ((string)(this["FragmentServicePlanSeg3"]));
            }
            set {
                this["FragmentServicePlanSeg3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Service Plan Seg 4 v0.1.docx")]
        public string FragmentServicePlanSeg4 {
            get {
                return ((string)(this["FragmentServicePlanSeg4"]));
            }
            set {
                this["FragmentServicePlanSeg4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Service Plan Seg 5 v0.1.docx")]
        public string FragmentServicePlanSeg5 {
            get {
                return ((string)(this["FragmentServicePlanSeg5"]));
            }
            set {
                this["FragmentServicePlanSeg5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\OAMPS Professional Fees Remunera" +
            "tion.docx")]
        public string FragementFeesRemuneration {
            get {
                return ((string)(this["FragementFeesRemuneration"]));
            }
            set {
                this["FragementFeesRemuneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\OAMPS Combined  Fee and commissi" +
            "on.docx")]
        public string FragementFeesCommission {
            get {
                return ((string)(this["FragementFeesCommission"]));
            }
            set {
                this["FragementFeesCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\UFI Declaration.doc")]
        public string FragmentUFI {
            get {
                return ((string)(this["FragmentUFI"]));
            }
            set {
                this["FragmentUFI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Terms of Engagement.docx")]
        public string FragmentTermsOfEngagement {
            get {
                return ((string)(this["FragmentTermsOfEngagement"]));
            }
            set {
                this["FragmentTermsOfEngagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_NewInsr_NoGAW_" +
            "NoFunding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_NewInsr_NoGAW_" +
            "YesFunding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_NewInsr_YesGAW" +
            "_NoFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr NoContact_NewInsr_YesGAW" +
            "_YesFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_ExistingInsr_" +
            "NoGAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_ExistingInsr_" +
            "NoGAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_ExistingInsr_" +
            "YesGAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_ExistingInsr_" +
            "YesGAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_NewInsr_NoGAW" +
            "_NoFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_NewInsr_NoGAW" +
            "_YesFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren Ltr YesContact_NewInsr_YesGA" +
            "W_YesFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren_Rpt_Purpose of Report SEG4an" +
            "d5.docx")]
        public string FragmentRRPurposeReport45 {
            get {
                return ((string)(this["FragmentRRPurposeReport45"]));
            }
            set {
                this["FragmentRRPurposeReport45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren_Rpt_Purpose of Report SEG2an" +
            "d3.docx")]
        public string FragmentRRPurposeReport23 {
            get {
                return ((string)(this["FragmentRRPurposeReport23"]));
            }
            set {
                this["FragmentRRPurposeReport23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Executive Summary_Fees_Commissio" +
            "n Only.docx")]
        public string FragmentRREexSumFeeCommission {
            get {
                return ((string)(this["FragmentRREexSumFeeCommission"]));
            }
            set {
                this["FragmentRREexSumFeeCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Executive Summary_Fees_Fee Only " +
            "and Combination.docx")]
        public string FragmentRREexSumFeeCombine {
            get {
                return ((string)(this["FragmentRREexSumFeeCombine"]));
            }
            set {
                this["FragmentRREexSumFeeCombine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Fragement Agenda Minutes.docx")]
        public string FragmentAGMinutes {
            get {
                return ((string)(this["FragmentAGMinutes"]));
            }
            set {
                this["FragmentAGMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Client Profile.docx")]
        public string FragmentClientProfile {
            get {
                return ((string)(this["FragmentClientProfile"]));
            }
            set {
                this["FragmentClientProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Pre-Renewal Questionnai" +
            "re.docx")]
        public string TemplatePrerenewalQuestionare {
            get {
                return ((string)(this["TemplatePrerenewalQuestionare"]));
            }
            set {
                this["TemplatePrerenewalQuestionare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\PR Questionare Approval Form.doc" +
            "x")]
        public string FragmentPRQApprovalForm {
            get {
                return ((string)(this["FragmentPRQApprovalForm"]));
            }
            set {
                this["FragmentPRQApprovalForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\PR Questionare Claims Made Warni" +
            "ng.docx")]
        public string FragmentPRQClaimsMadeWarning {
            get {
                return ((string)(this["FragmentPRQClaimsMadeWarning"]));
            }
            set {
                this["FragmentPRQClaimsMadeWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Ren_Rpt Purpose of Report.docx")]
        public string FragmentRRPurposeReportGeneric {
            get {
                return ((string)(this["FragmentRRPurposeReportGeneric"]));
            }
            set {
                this["FragmentRRPurposeReportGeneric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Blank Fragment Base.docx")]
        public string BlankFSGFragement {
            get {
                return ((string)(this["BlankFSGFragement"]));
            }
            set {
                this["BlankFSGFragement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\PlacementSlipConditions.docx")]
        public string PlacementSlipConditionsFragement {
            get {
                return ((string)(this["PlacementSlipConditionsFragement"]));
            }
            set {
                this["PlacementSlipConditionsFragement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Information for Policy.docx")]
        public string InformationForPolicyFragment {
            get {
                return ((string)(this["InformationForPolicyFragment"]));
            }
            set {
                this["InformationForPolicyFragment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Contracting Procedure.docx")]
        public string FragmentContractingProcedure {
            get {
                return ((string)(this["FragmentContractingProcedure"]));
            }
            set {
                this["FragmentContractingProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\InsuranceProposalShortProgramSum" +
            "mary.docx")]
        public string InsuranceProposalShortProgramSummary {
            get {
                return ((string)(this["InsuranceProposalShortProgramSummary"]));
            }
            set {
                this["InsuranceProposalShortProgramSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Client Profile Insurance Proposa" +
            "l Short.docx")]
        public string FragmentClientProfileShortFormProposal {
            get {
                return ((string)(this["FragmentClientProfileShortFormProposal"]));
            }
            set {
                this["FragmentClientProfileShortFormProposal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Blank Fragment Base Olly.docx")]
        public string BlankFragmentBaseOlly {
            get {
                return ((string)(this["BlankFragmentBaseOlly"]));
            }
            set {
                this["BlankFragmentBaseOlly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Class of Insurance.docx")]
        public string FragmentClassOfInsurance {
            get {
                return ((string)(this["FragmentClassOfInsurance"]));
            }
            set {
                this["FragmentClassOfInsurance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\InsuranceManualProgramSummary.do" +
            "cx")]
        public string InsuranceManualProgramSummary {
            get {
                return ((string)(this["InsuranceManualProgramSummary"]));
            }
            set {
                this["InsuranceManualProgramSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\OAMPSWordTemplates\\Insurance Manual.docx")]
        public string TemplateInsuranceManual {
            get {
                return ((string)(this["TemplateInsuranceManual"]));
            }
            set {
                this["TemplateInsuranceManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Segment 1 graphic.docx")]
        public string Segment1Graphic {
            get {
                return ((string)(this["Segment1Graphic"]));
            }
            set {
                this["Segment1Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Segment 2 graphic.docx")]
        public string Segment2Graphic {
            get {
                return ((string)(this["Segment2Graphic"]));
            }
            set {
                this["Segment2Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Segment 3 graphic.docx")]
        public string Segment3Graphic {
            get {
                return ((string)(this["Segment3Graphic"]));
            }
            set {
                this["Segment3Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Segment 4 graphic.docx")]
        public string Segment4Graphic {
            get {
                return ((string)(this["Segment4Graphic"]));
            }
            set {
                this["Segment4Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://%ProgramData%\\AJG\\CSS Templates\\Fragments\\Segment 5 graphic.docx")]
        public string Segment5Graphic {
            get {
                return ((string)(this["Segment5Graphic"]));
            }
            set {
                this["Segment5Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This template has been updated and Word will now exit.")]
        public string UpdateMessage {
            get {
                return ((string)(this["UpdateMessage"]));
            }
            set {
                this["UpdateMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%ProgramData%\\AJG\\CSS Templates")]
        public string LocalFullPathRoot {
            get {
                return ((string)(this["LocalFullPathRoot"]));
            }
            set {
                this["LocalFullPathRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_fvs.txt")]
        public string FieldValuesFileEnding {
            get {
                return ((string)(this["FieldValuesFileEnding"]));
            }
            set {
                this["FieldValuesFileEnding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%ProgramData%\\AJG\\CSS Templates\\Logs")]
        public string ErrorLogPath {
            get {
                return ((string)(this["ErrorLogPath"]));
            }
            set {
                this["ErrorLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%ProgramData%\\AJG\\CSS Templates\\UsageLogQueue.txt")]
        public string UsageLogQueue {
            get {
                return ((string)(this["UsageLogQueue"]));
            }
            set {
                this["UsageLogQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMI")]
        public string PeoplePickerSearchDomain {
            get {
                return ((string)(this["PeoplePickerSearchDomain"]));
            }
            set {
                this["PeoplePickerSearchDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Australia Broking,OU=ANZ Australia,OU=ANZ Locations,OU=ANZ,OU=LOCATIONS,DC=smi" +
            ",DC=ajgco,DC=com")]
        public string PeoplePickerSearchOU {
            get {
                return ((string)(this["PeoplePickerSearchOU"]));
            }
            set {
                this["PeoplePickerSearchOU"] = value;
            }
        }
    }
}
