//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMPS.Office.Word.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPS Branding")]
        public string GraphicsPictureLibraryTitle {
            get {
                return ((string)(this["GraphicsPictureLibraryTitle"]));
            }
            set {
                this["GraphicsPictureLibraryTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Company Logos")]
        public string GraphicsPictureLibraryTitleLogos {
            get {
                return ((string)(this["GraphicsPictureLibraryTitleLogos"]));
            }
            set {
                this["GraphicsPictureLibraryTitleLogos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Class of Insurance")]
        public string MajorPolicyClassesListName {
            get {
                return ((string)(this["MajorPolicyClassesListName"]));
            }
            set {
                this["MajorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Policy Type")]
        public string MinorPolicyClassesListName {
            get {
                return ((string)(this["MinorPolicyClassesListName"]));
            }
            set {
                this["MinorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyFragments")]
        public string PolicyFragmentsListName {
            get {
                return ((string)(this["PolicyFragmentsListName"]));
            }
            set {
                this["PolicyFragmentsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approved Insurers List")]
        public string ApprovedInsurersListName {
            get {
                return ((string)(this["ApprovedInsurersListName"]));
            }
            set {
                this["ApprovedInsurersListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentsListName {
            get {
                return ((string)(this["GeneralFragmentsListName"]));
            }
            set {
                this["GeneralFragmentsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFITo {
            get {
                return ((string)(this["EmailAddressUFITo"]));
            }
            set {
                this["EmailAddressUFITo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFIFrom {
            get {
                return ((string)(this["EmailAddressUFIFrom"]));
            }
            set {
                this["EmailAddressUFIFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMTP {
            get {
                return ((string)(this["SMTP"]));
            }
            set {
                this["SMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Guide")]
        public string MinorQuestionClassesListName {
            get {
                return ((string)(this["MinorQuestionClassesListName"]));
            }
            set {
                this["MinorQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Category")]
        public string TopLevelQuestionClassesListName {
            get {
                return ((string)(this["TopLevelQuestionClassesListName"]));
            }
            set {
                this["TopLevelQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyFragments")]
        public string PolicyFragmentKeysListName {
            get {
                return ((string)(this["PolicyFragmentKeysListName"]));
            }
            set {
                this["PolicyFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentKeysListName {
            get {
                return ((string)(this["GeneralFragmentKeysListName"]));
            }
            set {
                this["GeneralFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/OAMPS%20Combined%20%20Fee%20and%20comm" +
            "ission.docx")]
        public string FragementFeesCommission {
            get {
                return ((string)(this["FragementFeesCommission"]));
            }
            set {
                this["FragementFeesCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Class%20of%20Insurance.docx")]
        public string FragmentClassOfInsurance {
            get {
                return ((string)(this["FragmentClassOfInsurance"]));
            }
            set {
                this["FragmentClassOfInsurance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://inside.obs.com.au/personal/colarod/OampsTemplates/")]
        public string SharePointContextUrl {
            get {
                return ((string)(this["SharePointContextUrl"]));
            }
            set {
                this["SharePointContextUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/CSS%20Templates/Insurance%20Renewal%20Report.doc" +
            "x")]
        public string TemplateInsuranceRenewalReport {
            get {
                return ((string)(this["TemplateInsuranceRenewalReport"]));
            }
            set {
                this["TemplateInsuranceRenewalReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/OAMPSWordTemplates/Renewal%20Letter.docx")]
        public string TemplateInsuranceRenewalLetter {
            get {
                return ((string)(this["TemplateInsuranceRenewalLetter"]));
            }
            set {
                this["TemplateInsuranceRenewalLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/OAMPSWordTemplates/Discovery%20Guide.docx")]
        public string TemplateDiscoveryGuide {
            get {
                return ((string)(this["TemplateDiscoveryGuide"]));
            }
            set {
                this["TemplateDiscoveryGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/OAMPSWordTemplates/Meeting%20Agenda.docx")]
        public string TemplateAgenda {
            get {
                return ((string)(this["TemplateAgenda"]));
            }
            set {
                this["TemplateAgenda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/General%20Advice%20Warniing%20Fragment" +
            ".docx")]
        public string FragmentWarning {
            get {
                return ((string)(this["FragmentWarning"]));
            }
            set {
                this["FragmentWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/FSG%20Fragment.docx")]
        public string FragmentFSG {
            get {
                return ((string)(this["FragmentFSG"]));
            }
            set {
                this["FragmentFSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Privacy%20Statement.docx")]
        public string FragmentPrivacy {
            get {
                return ((string)(this["FragmentPrivacy"]));
            }
            set {
                this["FragmentPrivacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Uninsured%20Risks%20Checklist.docx")]
        public string FragmentUninsuredRisks {
            get {
                return ((string)(this["FragmentUninsuredRisks"]));
            }
            set {
                this["FragmentUninsuredRisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Important%20Notices.docx")]
        public string FragmentStatutory {
            get {
                return ((string)(this["FragmentStatutory"]));
            }
            set {
                this["FragmentStatutory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_NoG" +
            "AW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_NoG" +
            "AW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_Yes" +
            "GAW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_Yes" +
            "GAW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Service%20Plan%20Seg%202%20v0.1.docx")]
        public string FragmentServicePlanSeg2 {
            get {
                return ((string)(this["FragmentServicePlanSeg2"]));
            }
            set {
                this["FragmentServicePlanSeg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Service%20Plan%20Seg%203%20v0.1.docx")]
        public string FragmentServicePlanSeg3 {
            get {
                return ((string)(this["FragmentServicePlanSeg3"]));
            }
            set {
                this["FragmentServicePlanSeg3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Service%20Plan%20Seg%204%20v0.1.docx")]
        public string FragmentServicePlanSeg4 {
            get {
                return ((string)(this["FragmentServicePlanSeg4"]));
            }
            set {
                this["FragmentServicePlanSeg4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Service%20Plan%20Seg%205%20v0.1.docx")]
        public string FragmentServicePlanSeg5 {
            get {
                return ((string)(this["FragmentServicePlanSeg5"]));
            }
            set {
                this["FragmentServicePlanSeg5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/OAMPS%20Professional%20Fees%20Remunera" +
            "tion.docx")]
        public string FragementFeesRemuneration {
            get {
                return ((string)(this["FragementFeesRemuneration"]));
            }
            set {
                this["FragementFeesRemuneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/UFI%20Declaration.doc")]
        public string FragmentUFI {
            get {
                return ((string)(this["FragmentUFI"]));
            }
            set {
                this["FragmentUFI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Terms%20of%20Engagement.docx")]
        public string FragmentTermsOfEngagement {
            get {
                return ((string)(this["FragmentTermsOfEngagement"]));
            }
            set {
                this["FragmentTermsOfEngagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_NewInsr_NoGAW_No" +
            "Funding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_NewInsr_NoGAW_Ye" +
            "sFunding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_NewInsr_YesGAW_N" +
            "oFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20NoContact_NewInsr_YesGAW_Y" +
            "esFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_No" +
            "GAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_No" +
            "GAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_Ye" +
            "sGAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_Ye" +
            "sGAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_NewInsr_NoGAW_N" +
            "oFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_NewInsr_NoGAW_Y" +
            "esFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_NewInsr_YesGAW_" +
            "NoFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Ren%20Ltr%20YesContact_NewInsr_YesGAW_" +
            "YesFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Purpose%20of%20Report%20SEG4and5.docx")]
        public string FragmentRRPurposeReport45 {
            get {
                return ((string)(this["FragmentRRPurposeReport45"]));
            }
            set {
                this["FragmentRRPurposeReport45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Purpose%20of%20Report%20SEG2and3.docx")]
        public string FragmentRRPurposeReport23 {
            get {
                return ((string)(this["FragmentRRPurposeReport23"]));
            }
            set {
                this["FragmentRRPurposeReport23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Executive%20Summary_Fees_Commission%20" +
            "Only.docx")]
        public string FragmentRREexSumFeeCommission {
            get {
                return ((string)(this["FragmentRREexSumFeeCommission"]));
            }
            set {
                this["FragmentRREexSumFeeCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Executive%20Summary_Fees_Fee%20Only%20" +
            "and%20Combination.docx")]
        public string FragmentRREexSumFeeCombine {
            get {
                return ((string)(this["FragmentRREexSumFeeCombine"]));
            }
            set {
                this["FragmentRREexSumFeeCombine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/personal/colarod/OampsTemplates/Fragments/Fragement%20Agenda%20Minutes.docx")]
        public string FragmentAGMinutes {
            get {
                return ((string)(this["FragmentAGMinutes"]));
            }
            set {
                this["FragmentAGMinutes"] = value;
            }
        }
    }
}
