//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMPS.Office.Word.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPS Branding")]
        public string GraphicsPictureLibraryTitle {
            get {
                return ((string)(this["GraphicsPictureLibraryTitle"]));
            }
            set {
                this["GraphicsPictureLibraryTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Company Logos")]
        public string GraphicsPictureLibraryTitleLogos {
            get {
                return ((string)(this["GraphicsPictureLibraryTitleLogos"]));
            }
            set {
                this["GraphicsPictureLibraryTitleLogos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Class of Insurance")]
        public string MajorPolicyClassesListName {
            get {
                return ((string)(this["MajorPolicyClassesListName"]));
            }
            set {
                this["MajorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Policy Type")]
        public string MinorPolicyClassesListName {
            get {
                return ((string)(this["MinorPolicyClassesListName"]));
            }
            set {
                this["MinorPolicyClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PreRenewalQuestionareMappings")]
        public string PreRenewalQuestionareMappingsListName {
            get {
                return ((string)(this["PreRenewalQuestionareMappingsListName"]));
            }
            set {
                this["PreRenewalQuestionareMappingsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approved Insurers List")]
        public string ApprovedInsurersListName {
            get {
                return ((string)(this["ApprovedInsurersListName"]));
            }
            set {
                this["ApprovedInsurersListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentsListName {
            get {
                return ((string)(this["GeneralFragmentsListName"]));
            }
            set {
                this["GeneralFragmentsListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFITo {
            get {
                return ((string)(this["EmailAddressUFITo"]));
            }
            set {
                this["EmailAddressUFITo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("daniel.colarossi@oamps.com.au")]
        public string EmailAddressUFIFrom {
            get {
                return ((string)(this["EmailAddressUFIFrom"]));
            }
            set {
                this["EmailAddressUFIFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMTP {
            get {
                return ((string)(this["SMTP"]));
            }
            set {
                this["SMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Guide")]
        public string MinorQuestionClassesListName {
            get {
                return ((string)(this["MinorQuestionClassesListName"]));
            }
            set {
                this["MinorQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Category")]
        public string TopLevelQuestionClassesListName {
            get {
                return ((string)(this["TopLevelQuestionClassesListName"]));
            }
            set {
                this["TopLevelQuestionClassesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyFragments")]
        public string PolicyFragmentKeysListName {
            get {
                return ((string)(this["PolicyFragmentKeysListName"]));
            }
            set {
                this["PolicyFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fragments")]
        public string GeneralFragmentKeysListName {
            get {
                return ((string)(this["GeneralFragmentKeysListName"]));
            }
            set {
                this["GeneralFragmentKeysListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Word Help Content")]
        public string HelpContentListName {
            get {
                return ((string)(this["HelpContentListName"]));
            }
            set {
                this["HelpContentListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage Reporting")]
        public string UsageReportingListName {
            get {
                return ((string)(this["UsageReportingListName"]));
            }
            set {
                this["UsageReportingListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quote Slip Schedules")]
        public string PolicySchedulesListName {
            get {
                return ((string)(this["PolicySchedulesListName"]));
            }
            set {
                this["PolicySchedulesListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Claims Procedures")]
        public string LibraryClaimsProcedures {
            get {
                return ((string)(this["LibraryClaimsProcedures"]));
            }
            set {
                this["LibraryClaimsProcedures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("proposal short document titles")]
        public string ListProposalShortDocumentTitles {
            get {
                return ((string)(this["ListProposalShortDocumentTitles"]));
            }
            set {
                this["ListProposalShortDocumentTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAMPSWordTemplates")]
        public string MainTemplatesLibraryName {
            get {
                return ((string)(this["MainTemplatesLibraryName"]));
            }
            set {
                this["MainTemplatesLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://templates.oamps.com.au/")]
        public string SharePointContextUrl {
            get {
                return ((string)(this["SharePointContextUrl"]));
            }
            set {
                this["SharePointContextUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/FSG%20Fragment_letter.docx")]
        public string FragmentFSGLetter {
            get {
                return ((string)(this["FragmentFSGLetter"]));
            }
            set {
                this["FragmentFSGLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/General%20Advice%20Warniing%20Fragment.docx")]
        public string FragmentWarning {
            get {
                return ((string)(this["FragmentWarning"]));
            }
            set {
                this["FragmentWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Insurance%20Renewal%20Report.docx")]
        public string TemplateInsuranceRenewalReport {
            get {
                return ((string)(this["TemplateInsuranceRenewalReport"]));
            }
            set {
                this["TemplateInsuranceRenewalReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Discovery%20Guide.docx")]
        public string TemplateDiscoveryGuide {
            get {
                return ((string)(this["TemplateDiscoveryGuide"]));
            }
            set {
                this["TemplateDiscoveryGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Meeting%20Agenda.docx")]
        public string TemplateAgenda {
            get {
                return ((string)(this["TemplateAgenda"]));
            }
            set {
                this["TemplateAgenda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/FSG%20Fragment.docx")]
        public string FragmentFSG {
            get {
                return ((string)(this["FragmentFSG"]));
            }
            set {
                this["FragmentFSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Privacy%20Statement.docx")]
        public string FragmentPrivacy {
            get {
                return ((string)(this["FragmentPrivacy"]));
            }
            set {
                this["FragmentPrivacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Uninsured%20Risks%20Checklist.docx")]
        public string FragmentUninsuredRisks {
            get {
                return ((string)(this["FragmentUninsuredRisks"]));
            }
            set {
                this["FragmentUninsuredRisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Important%20Notices.docx")]
        public string FragmentStatutory {
            get {
                return ((string)(this["FragmentStatutory"]));
            }
            set {
                this["FragmentStatutory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_NoGAW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_NoGAW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_YesGAW_NoFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_ExistingInsr_YesGAW_YesFunding.docx")]
        public string FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Service%20Plan%20Seg%202%20v0.1.docx")]
        public string FragmentServicePlanSeg2 {
            get {
                return ((string)(this["FragmentServicePlanSeg2"]));
            }
            set {
                this["FragmentServicePlanSeg2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Service%20Plan%20Seg%203%20v0.1.docx")]
        public string FragmentServicePlanSeg3 {
            get {
                return ((string)(this["FragmentServicePlanSeg3"]));
            }
            set {
                this["FragmentServicePlanSeg3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Service%20Plan%20Seg%204%20v0.1.docx")]
        public string FragmentServicePlanSeg4 {
            get {
                return ((string)(this["FragmentServicePlanSeg4"]));
            }
            set {
                this["FragmentServicePlanSeg4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Service%20Plan%20Seg%205%20v0.1.docx")]
        public string FragmentServicePlanSeg5 {
            get {
                return ((string)(this["FragmentServicePlanSeg5"]));
            }
            set {
                this["FragmentServicePlanSeg5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/OAMPS%20Professional%20Fees%20Remuneration.docx")]
        public string FragementFeesRemuneration {
            get {
                return ((string)(this["FragementFeesRemuneration"]));
            }
            set {
                this["FragementFeesRemuneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/OAMPS%20Combined%20%20Fee%20and%20commission.docx")]
        public string FragementFeesCommission {
            get {
                return ((string)(this["FragementFeesCommission"]));
            }
            set {
                this["FragementFeesCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/UFI%20Declaration.doc")]
        public string FragmentUFI {
            get {
                return ((string)(this["FragmentUFI"]));
            }
            set {
                this["FragmentUFI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Terms%20of%20Engagement.docx")]
        public string FragmentTermsOfEngagement {
            get {
                return ((string)(this["FragmentTermsOfEngagement"]));
            }
            set {
                this["FragmentTermsOfEngagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_NewInsr_NoGAW_NoFunding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_NewInsr_NoGAW_YesFunding.docx")]
        public string FragmentRLNoContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_NewInsr_YesGAW_NoFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20NoContact_NewInsr_YesGAW_YesFunding.docx")]
        public string FragmentRLNoContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLNoContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_NoGAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_NoGAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_YesGAW_NoFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_ExistingInsr_YesGAW_YesFunding.docx")]
        public string FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_ExistingInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_NewInsr_NoGAW_NoFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_NewInsr_NoGAW_YesFunding.docx")]
        public string FragmentRLYesContact_NewInsr_NoGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_NoGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_NewInsr_YesGAW_NoFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_NoFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_NoFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren%20Ltr%20YesContact_NewInsr_YesGAW_YesFunding.docx")]
        public string FragmentRLYesContact_NewInsr_YesGAW_YesFunding {
            get {
                return ((string)(this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"]));
            }
            set {
                this["FragmentRLYesContact_NewInsr_YesGAW_YesFunding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren_Rpt_Purpose%20of%20Report%20SEG4and5.docx")]
        public string FragmentRRPurposeReport45 {
            get {
                return ((string)(this["FragmentRRPurposeReport45"]));
            }
            set {
                this["FragmentRRPurposeReport45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren_Rpt_Purpose%20of%20Report%20SEG2and3.docx")]
        public string FragmentRRPurposeReport23 {
            get {
                return ((string)(this["FragmentRRPurposeReport23"]));
            }
            set {
                this["FragmentRRPurposeReport23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Executive%20Summary_Fees_Commission%20Only.docx")]
        public string FragmentRREexSumFeeCommission {
            get {
                return ((string)(this["FragmentRREexSumFeeCommission"]));
            }
            set {
                this["FragmentRREexSumFeeCommission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Executive%20Summary_Fees_Fee%20Only%20and%20Combination.docx")]
        public string FragmentRREexSumFeeCombine {
            get {
                return ((string)(this["FragmentRREexSumFeeCombine"]));
            }
            set {
                this["FragmentRREexSumFeeCombine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Fragement%20Agenda%20Minutes.docx")]
        public string FragmentAGMinutes {
            get {
                return ((string)(this["FragmentAGMinutes"]));
            }
            set {
                this["FragmentAGMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Client%20Profile.docx")]
        public string FragmentClientProfile {
            get {
                return ((string)(this["FragmentClientProfile"]));
            }
            set {
                this["FragmentClientProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Pre-Renewal%20Questionnaire.docx")]
        public string TemplatePrerenewalQuestionare {
            get {
                return ((string)(this["TemplatePrerenewalQuestionare"]));
            }
            set {
                this["TemplatePrerenewalQuestionare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/PR%20Questionare%20Approval%20Form.docx")]
        public string FragmentPRQApprovalForm {
            get {
                return ((string)(this["FragmentPRQApprovalForm"]));
            }
            set {
                this["FragmentPRQApprovalForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/PR%20Questionare%20Claims%20Made%20Warning.docx")]
        public string FragmentPRQClaimsMadeWarning {
            get {
                return ((string)(this["FragmentPRQClaimsMadeWarning"]));
            }
            set {
                this["FragmentPRQClaimsMadeWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Ren_Rpt%20Purpose%20of%20Report.docx")]
        public string FragmentRRPurposeReportGeneric {
            get {
                return ((string)(this["FragmentRRPurposeReportGeneric"]));
            }
            set {
                this["FragmentRRPurposeReportGeneric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Blank%20Fragment%20Base.docx")]
        public string BlankFSGFragement {
            get {
                return ((string)(this["BlankFSGFragement"]));
            }
            set {
                this["BlankFSGFragement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Generic%20Letter.docx")]
        public string TemplateGenericLetter {
            get {
                return ((string)(this["TemplateGenericLetter"]));
            }
            set {
                this["TemplateGenericLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Renewal%20Letter.docx")]
        public string TemplateInsuranceRenewalLetter {
            get {
                return ((string)(this["TemplateInsuranceRenewalLetter"]));
            }
            set {
                this["TemplateInsuranceRenewalLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/QuoteSlip.docx")]
        public string TemplateQuoteSlip {
            get {
                return ((string)(this["TemplateQuoteSlip"]));
            }
            set {
                this["TemplateQuoteSlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/PlacementSlipConditions.docx")]
        public string PlacementSlipConditionsFragement {
            get {
                return ((string)(this["PlacementSlipConditionsFragement"]));
            }
            set {
                this["PlacementSlipConditionsFragement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Information%20for%20Policy.docx")]
        public string InformationForPolicyFragment {
            get {
                return ((string)(this["InformationForPolicyFragment"]));
            }
            set {
                this["InformationForPolicyFragment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Contracting%20Procedure.docx")]
        public string FragmentContractingProcedure {
            get {
                return ((string)(this["FragmentContractingProcedure"]));
            }
            set {
                this["FragmentContractingProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/InsuranceProposalShortProgramSummary.docx")]
        public string InsuranceProposalShortProgramSummary {
            get {
                return ((string)(this["InsuranceProposalShortProgramSummary"]));
            }
            set {
                this["InsuranceProposalShortProgramSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Client%20Profile%20Insurance%20Proposal%20Short.docx")]
        public string FragmentClientProfileShortFormProposal {
            get {
                return ((string)(this["FragmentClientProfileShortFormProposal"]));
            }
            set {
                this["FragmentClientProfileShortFormProposal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Blank%20Fragment%20Base%20Olly.docx")]
        public string BlankFragmentBaseOlly {
            get {
                return ((string)(this["BlankFragmentBaseOlly"]));
            }
            set {
                this["BlankFragmentBaseOlly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Class%20of%20Insurance.docx")]
        public string FragmentClassOfInsurance {
            get {
                return ((string)(this["FragmentClassOfInsurance"]));
            }
            set {
                this["FragmentClassOfInsurance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/InsuranceManualProgramSummary.docx")]
        public string InsuranceManualProgramSummary {
            get {
                return ((string)(this["InsuranceManualProgramSummary"]));
            }
            set {
                this["InsuranceManualProgramSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/OAMPSWordTemplates/Insurance%20Manual.docx")]
        public string TemplateInsuranceManual {
            get {
                return ((string)(this["TemplateInsuranceManual"]));
            }
            set {
                this["TemplateInsuranceManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Segment%201%20graphic.docx")]
        public string Segment1Graphic {
            get {
                return ((string)(this["Segment1Graphic"]));
            }
            set {
                this["Segment1Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Segment%202%20graphic.docx")]
        public string Segment2Graphic {
            get {
                return ((string)(this["Segment2Graphic"]));
            }
            set {
                this["Segment2Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Segment%203%20graphic.docx")]
        public string Segment3Graphic {
            get {
                return ((string)(this["Segment3Graphic"]));
            }
            set {
                this["Segment3Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Segment%204%20graphic.docx")]
        public string Segment4Graphic {
            get {
                return ((string)(this["Segment4Graphic"]));
            }
            set {
                this["Segment4Graphic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Fragments/Segment%205%20graphic.docx")]
        public string Segment5Graphic {
            get {
                return ((string)(this["Segment5Graphic"]));
            }
            set {
                this["Segment5Graphic"] = value;
            }
        }
    }
}
